### ISSUE TITLE
[FEAT] Flask와 Springboot 통신 테스트

### ISSUE THREAD

**Issue by igyuwon** [TEAM-HPP/HAPPY-PAW-PET#13]
## 🐾 Description

Flask와 Springboot 통신 테스트

## 🐾 To-do

- [x] FlaskClient.java 추가
- [x] Application_config 수정
- [x] File_config 수정
