### ISSUE TITLE
[FEAT] 관리자페이지 구글 애널리틱스 API 연동하기

### ISSUE THREAD

**Issue by eogksdls** [TEAM-HPP/HAPPY-PAW-PET#21]
## 🐾 Description
구글 애널리틱스 api를 python으로 받아와서,
spring javascript 클라이언트 페이지와 연결 -> chartjs 생성하기

## 🐾 To-do

- [x] 유기동물 상세페이지 css 이미지 border 지움
- [x] 구글 애널리틱스 구성(태그 생성 후 페이지 header 부분에 붙여넣기)
- [x] access token 발급 후, api 불러오는 python 코드 작성 -> javascript ajax으로 값을 못받아와서.. 따로 json 저장하는 파일 만들음
- [x] json 데이터 저장 파일 생성(Dto, Service)
- [x] javascript 연결
- [x] chartjs로 시각화하기

## 🐾 ETC

python으로 구글 애널리틱스 api 받아오는 것까지 완료했지만,
javascript 연결 실패(개발 프로그램 한계ㅜㅜ)

json 데이터를 따로 저장해서 그 데이터를 불러오는 방향으로 수정함.
-> 이후 django 이용해서 연결해보기
