### ISSUE TITLE
[REFACTOR] PetDiagnosis, CheckTool 수정

### ISSUE THREAD

**Issue by igyuwon** [TEAM-HPP/HAPPY-PAW-PET#3]
## 🐾 Description

PetDiagnosis, CheckTool 수정

## 🐾 To-do

- [x] PetDiagnosis.dto 수정
- [x] PetDiagnosis.dao 수정
- [x] petDiagnosisMapping.xml 수정
- [x] CheckTool.jsp 수정
