### ISSUE TITLE
[DESIGN] 메인페이지 section 스크롤

### ISSUE THREAD

**Issue by eogksdls** [TEAM-HPP/HAPPY-PAW-PET#50]
## 🐾 Description

Happypawpet 메인페이지 
한 블럭 당 section을 부여하여 스크롤 시 한 개의 section이 보여지게 CSS 수정
## 🐾 To-do

- [x] 기존의 div로 묶여있던 블럭을 section으로 수정
- [x] y방향으로 스크롤 강제
- [x] 스크롤바 hidden
- [x] 스크롤 시 한 개의 section씩 보여지도록 CSS 수정
