### ISSUE TITLE
[FEAT] 관리자페이지 Google Analytics API 연결 후 차트 그리기

### ISSUE THREAD

**Issue by eogksdls** [TEAM-HPP/HAPPY-PAW-PET#58]
## 🐾 Description

구글 애널리틱스 api -> java 연동
client 화면페이지로 json 형태의 데이터를 받아 차트로 시각화

## 🐾 To-do

- [x] pom.xml에 Google Maven 리포지토리 추가
- [x] GA4 api -> java 연결코드 작성
- [x] 받아온 json데이터로 화면 차트 그리기
